apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox
    environment: dev
spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    command: ["sh", "-c", "echo Hello Kanha && sleep 3600"]
