apiVersion: v1
kind: Pod
metadata:
  name: redis-pod-custom
  labels:
    app: redis
    environment: production
    team: devops
spec:
  containers:
  - name: redis-container
    image: redis:latest
    ports:
    - containerPort: 6379
